### PR TITLE
Changes to show page.

### PR DESCRIPTION
**Pull request by saritaphoo**

### CODE REVIEW

**Review by jsmli — APPROVED** [review]

**Comment by saritaphoo** [comment]
[Include doughnut chart for percent spoken on 'show' page.](https://trello.com/c/Vdvxbj6G/27-include-doughnut-chart-for-percent-spoken-on-show-page)

**Comment by saritaphoo** [comment]
[Include chart for action items.](https://trello.com/c/OmuOJBgK/26-include-chart-for-action-items)

**Comment by saritaphoo** [comment]
[Include hesitation and interruption charts.](https://trello.com/c/fLHosRBs/24-include-hesitation-and-interruption-charts)

**Comment by saritaphoo** [comment]
[Improve the display of meetings 'show' page.](https://trello.com/c/xB0qLv81/25-improve-the-display-of-meetings-show-page)

**Pull request merged**
